cluster.name: javacafe-cluster
node.name: javacafe-node1
network.host: 0.0.0.0
http.port: 9200
transport.tcp.port: 9300
node.master: true
node.data: true
discovery.type: single-node
path.repo: ["/es/book_backup/search_example", "/es/book_backup/agg_example"]
